; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=x86_64-- -stop-after=finalize-isel -o - %s | FileCheck %s
define i32 @bsr(i32 noundef %v) {
  ; CHECK-LABEL: name: bsr
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   INLINEASM &"", 0 /* attdialect */, 1076101130 /* regdef:GR32 spillable */, def %1
  ; CHECK-NEXT:   $eax = COPY %1
  ; CHECK-NEXT:   RET 0, $eax
entry:
  %0 = call i32 asm "", "=rm"()
  ret i32 %0
}
